### ISSUE TITLE
NameError: name 'Generator' is not defined

### ISSUE THREAD

**Issue by essen900718** [Prikalel/django-xss-example#1]
I encounter this problem while running command `python3 runfuzz.py`, do I did something wrong ?

```
File "/Users/xxx/Desktop/django-xss-example/runfuzz.py", line 24, in <module>
    class Fuzzer:
  File "/Users/xxx/Desktop/django-xss-example/runfuzz.py", line 26, in Fuzzer
    g: Generator
       ^^^^^^^^^
NameError: name 'Generator' is not defined. Did you mean: 'GeneratorTool'?
```

**Comment by Prikalel** [comment]
did you install grammarinator? which python version do you using? is `grammarinator-generate` & `grammarinator-process` in yor PATH?

I need some more info to help through I remember getting the same error at some point

**Comment by essen900718** [comment]
> did you install grammarinator? which python version do you using? is `grammarinator-generate` & `grammarinator-process` in yor PATH?
> 
> I need some more info to help through I remember getting the same error at some point

Thanks for your reply.

Yes, I have installed grammarinator, and I can import `grammarinator.generate` and `grammarinator.process` as well. I'm using python 3.12.0.

The following is my enviroment:
```
Package                Version
---------------------- ---------
antlerinator           1!3.0.0
antlr4-python3-runtime 4.13.0
asgiref                3.7.2
async-generator        1.10
attrs                  23.1.0
autopep8               2.0.2
Brotli                 1.1.0
certifi                2023.7.22
charset-normalizer     3.1.0
colorama               0.4.6
Django                 4.0.1
exceptiongroup         1.1.1
grammarinator          23.7
h11                    0.14.0
idna                   3.4
inators                2.1.0
Jinja2                 3.1.2
MarkupSafe             2.1.2
numpy                  1.26.1
outcome                1.2.0
packaging              23.1
pandas                 2.0.2
pip                    23.3
plotly                 5.14.1
progress               1.6
pycodestyle            2.10.0
PySocks                1.7.1
python-dateutil        2.8.2
python-dotenv          1.0.0
pytz                   2023.3
requests               2.31.0
selenium               4.9.1
setuptools             68.2.2
six                    1.16.0
sniffio                1.3.0
sortedcontainers       2.4.0
sqlparse               0.4.4
tenacity               8.2.2
tomli                  2.0.1
tqdm                   4.65.0
trio                   0.22.0
trio-websocket         0.10.2
typing_extensions      4.6.3
tzdata                 2023.3
urllib3                2.0.2
webdriver-manager      3.8.6
wheel                  0.41.2
wsproto                1.2.0
```

**Comment by Prikalel** [comment]
Sorry for too late answer.
Ok, I just tested and I now know what the problem is.
You know, you didn't read README )))
In README you can see that grammarinator must be installed using git, not pip.

If you install the package like this:

```bash
pip install grammarinator
```

Yes, you will get the error.

But. If you install the same package like this:

```bash
pip install -r requirements.txt # I don't know why you didn't that like this
# or
pip install git+https://github.com/renatahodovan/grammarinator.git@e34333bfeee849fc88d6680efe15f62c722114b3 # using the correct sha commit
```

You will not get the error.

The next time before creating a issue, please, read a pinned README (if you don't know Russian language, you can easily translate the script with any online translator)

**Comment by Prikalel** [comment]
Please, reopen the issue if you still get some troubles.
Or create a new one.

**Comment by essen900718** [comment]
Got it. Thanks for your reply.
